site_name: Container Shipment EDA reference implementation
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc
nav:
  - Welcome: index.md
  - Business problem statement:
    - Introduction: introduction.md
    - Event storming analysis: ./analysis/readme.md
  - Design considerations and microservice identifications: ./design/readme.md
  - Architecture: ./design/architecture.md
  - Development practices:
    - Order microservice with CQRS and Event Sourcing: https://ibm-cloud-architecture.github.io/refarch-kc-order-ms
    - Container microservice with event sourcing and Kafka streams: https://ibm-cloud-architecture.github.io/refarch-kc-container-ms/kstreams/
    - Container microservice with Python:  https://ibm-cloud-architecture.github.io/refarch-kc-container-ms/flask
    - Container microservice with Springboot - Spring Kafka and PostgreSQL:  https://ibm-cloud-architecture.github.io/refarch-kc-container-ms/springboot
  - Related repositories: ./deployments/reposlist.md
  - Deployments:
    - Run locally with Docker Compose: ./deployments/local.md
    - Run on IBM Cloud Kubernetes Services: ./deployments/iks.md
    - Run on IBM Cloud Private: ./deployments/icp.md
  - Demonstration: ./demo/readme.md
  - Integration tests: ./itg-tests/README.md

theme: 
  name: material
extra_css: ["extra.css"]
