site_name: Container Shipment EDA reference implementation
repo_url: https://github.com/ibm-cloud-architecture/refarch-kc
nav:
  - Home: index.md
  - Business Problem Statement:
    - Introduction: introduction.md
    - Event storming analysis: ./analysis/readme.md
  - Design considerations and microservice identifications: ./design/readme.md
  - Architecture: ./design/architecture.md
  - Related repositories: ./deployments/reposlist.md
  - Deployments:
    - Run locally: ./deployments/local.md
    - Run on IBM Cloud Kubernetes Services: ./deployments/iks.md
    - Run on IBM Cloud Private: ./deployments/icp.md
  - Demonstration: ./demo/readme.md
  - Integration tests: ./itg-tests/README.md

theme: 
  name: material
extra_css: ["extra.css"]
