version: '3'
services:
    simulator:
        image: ibmcase/kc-fleetms:latest
        hostname: fleetms
        ports:
            - "9080:9080"
            - "9443:9443"
        environment:
            KAFKA_ENV: LOCAL
            KAFKA_BROKERS: kafka1:9092
    web:
        image: ibmcase/kc-ui:latest
        hostname: kcui
        ports:
            - "3000:3000"
        environment:
            KAFKA_BROKERS: kafka1:9092
            FLEET_MS_URL: http://simulator:9080/fleetms
            ORDER_MS_URL: http://ordercmd:10080/orders
            ORDER_QUERY_MS_URL: http://orderquery:11080/orders
        depends_on:
            - simulator
            - ordercmd 
            - orderquery
    ordercmd:
        image: ibmcase/kc-ordercmdms:latest
        hostname: ordercmd
        ports:
            - "10080:9080"
        environment:
            KAFKA_ENV: LOCAL
            KAFKA_BROKERS: kafka1:9092
        depends_on:
            - simulator            
    orderquery:
        image: ibmcase/kc-orderqueryms:latest
        hostname: orderquery
        ports:
            - "11080:9080"
        environment:
            KAFKA_ENV: LOCAL
            KAFKA_BROKERS: kafka1:9092
        depends_on:
            - simulator
