version: '3'
services:
    simulator:
        image: ibmcase/kc-fleetms:latest
        hostname: fleetms
        ports:
            - "9080:9080"
            - "9443:9443"
        environment:
            KAFKA_ENV: LOCAL
            KAFKA_BROKERS: kafka1:9092
    web:
        image: ibmcase/kc-ui:latest
        hostname: kcui
        ports:
            - "3000:3000"
        environment:
            KAFKA_BROKERS: kafka1:9092
            FLEET_MS_URL: http://simulator:9080/fleetms
        depends_on:
            - simulator