version: '3'
services:
    simulator:
        image: ibmcase/kc-fleetms:latest
        hostname: fleetms
        ports:
            - "9080:9080"
            - "9443:9443"
        environment:
            KAFKA_ENV: LOCAL
            KAFKA_BROKERS: kafka1:9092
    web:
        image: ibmcase/kc-ui:latest
        hostname: kcsolution
        ports:
            - "3010:3010"
        environment:
            KAFKA_BROKERS: kafka1:9092
            FLEET_MS_URL: http://simulator:9080/fleetms
            ORDER_MS_URL: http://ordercmd:9080/orders
            ORDER_QUERY_MS_URL: http://orderquery:9080/orders
        depends_on:
            - simulator
            - ordercmd 
            - orderquery
            - voyages
    ordercmd:
        image: ibmcase/kc-ordercmdms:latest
        hostname: ordercmd
        ports:
            - "10080:9080"
        environment:
            KAFKA_ENV: LOCAL
            KAFKA_BROKERS: kafka1:9092
    orderquery:
        image: ibmcase/kc-orderqueryms:latest
        hostname: orderquery
        ports:
            - "11080:9080"
        environment:
            KAFKA_ENV: LOCAL
            KAFKA_BROKERS: kafka1:9092
    voyages:
        image: ibmcase/kc-voyagesms:latest
        hostname: voyages
        ports:
            - "3100:3000"
