apiVersion: v1,
kind: PersistentVolume,
metadata:
    name: posgresql-pv,
spec:
    capacity:
      storage: 10Gi
    hostPath:
      path: /bitnami/postgresql,
      type: ""
    accessModes:
      ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain